[package]
name = "bam2bedgraph"
version = "0.1.0"
authors = ["Ben Booth <benwbooth@gmail.com>"]

[dependencies]
argparse = "*"
regex = "*"
rust-htslib = "*"

#[dependencies.rust-htslib]
#git = "https://github.com/rust-bio/rust-htslib.git"
