[package]
name = "bam2bedgraph"
version = "1.0.0"
authors = ["Ben Booth <benwbooth@gmail.com>"]

[dependencies]
regex = "*"
failure = "*"
structopt = "*"
structopt-derive = "*"
bio = "*"
csv = "1.0.0-beta.5"
itertools = "*"
url = "*"
lazy_static = "*"
serde_derive = "*"
serde_json = "*"
unindent = "*"
futures = "*"
futures-cpupool = "*"
num_cpus = "*"
ordered-float = "*"
duct = "*"

[dependencies.rust-htslib]
git = "https://github.com/rust-bio/rust-htslib.git"

[dependencies.serde]
version = "*"
features = ["std"]

[dependencies.linked-hash-map]
version = "*"
features = ["serde_impl"]

[dependencies.concurrent-hashmap]
version = "*"
default-features = false

[lib]
name = "bam2bedgraph"
path = "src/lib.rs"

[[bin]]
name = "bam2bedgraph"
path = "src/bam2bedgraph.rs"

[[bin]]
name = "intronrpkm"
path = "src/intronrpkm.rs"

[[bin]]
name = "cassette_lengths"
path = "src/cassette_lengths.rs"

[[bin]]
name = "rpkm"
path = "src/rpkm.rs"

[[bin]]
name = "adjusted_intron_cov"
path = "src/adjusted_intron_cov.rs"

[profile.dev]
opt-level = 2
