[package]
name = "bam2bedgraph"
version = "1.0.0"
authors = ["Ben Booth <benwbooth@gmail.com>"]

[dependencies]
regex = "*"
error-chain = "*"
memrange = "*"
structopt = "*"
structopt-derive = "*"

[dependencies.theban_interval_tree]
git = "https://github.com/theban/interval-tree.git"

[dependencies.rust-htslib]
git = "https://github.com/rust-bio/rust-htslib.git"
