[package]
name = "bam2bedgraph"
version = "1.0.0"
authors = ["Ben Booth <benwbooth@gmail.com>"]

[dependencies]
regex = "*"
error-chain = "*"
structopt = "*"
structopt-derive = "*"
rayon = "*"
bio = "*"
csv = "*"
peakbag = "*"
itertools = "*"

[dependencies.rust-htslib]
git = "https://github.com/rust-bio/rust-htslib.git"

[lib]
name = "bam2bedgraph"
path = "src/lib.rs"

[[bin]]
name = "bam2bedgraph"
path = "src/bam2bedgraph.rs"

[[bin]]
name = "intronrpkm"
path = "src/intronrpkm.rs"
